ALTER TABLE sites ADD CONSTRAINT PRIMARY KEY(siteID);
ALTER TABLE blocks ADD CONSTRAINT PRIMARY KEY(blockID);
ALTER TABLE plots ADD CONSTRAINT PRIMARY KEY(plotID);
ALTER TABLE turfs ADD CONSTRAINT PRIMARY KEY(turfID);
ALTER TABLE taxon ADD CONSTRAINT PRIMARY KEY(species);
ALTER TABLE turfEnvironment ADD CONSTRAINT PRIMARY KEY(turfID,year);
ALTER TABLE subTurfEnvironment ADD CONSTRAINT PRIMARY KEY(turfID,subTurf,year);
ALTER TABLE turfCommunity ADD CONSTRAINT PRIMARY KEY(turfID,year,species);
ALTER TABLE subTurfCommunity ADD CONSTRAINT PRIMARY KEY(turfID,subTurf,year,species);
ALTER TABLE mergedictionary ADD CONSTRAINT PRIMARY KEY(oldID);


ALTER TABLE blocks ADD FOREIGN KEY(siteID) REFERENCES sites(siteID);
ALTER TABLE blocks ADD FOREIGN KEY(siteID) REFERENCES sites(siteID);
