---
title: "Subturf Maps"
author: "Francesca Jaroszynska"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: pdf_document
classoption: a4paper
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::read_chunk('../graminoidRemovals/loadData.R')
```


```{r importChunk}
#load packages
library("tidyr")
library("plyr")
library("DBI")# also needs RMySQL installed
library("dplyr")
library("ggplot2")

#make database connection
con <- dbConnect(RMySQL::MySQL(), group = "seedclim")

#load cover data and subturf data
```


```{r my.GR.data.import}
```


```{r subturf.GR.import}
```

```{r}
#merge cover and subturf
subturf_cover_thin <- full_join(my.GR.data, subturf.GR)

subturf_cover_thin$problems[is.na(subturf_cover_thin$cover)] <- "no cover"
subturf_cover_thin$problems[is.na(subturf_cover_thin$subTurf)] <- "no subturf"
subturf_cover_thin$problems[is.na(subturf_cover_thin$problems)] <- "ok"
subturf_cover_thin$problems <- as.factor(subturf_cover_thin$problems)

```

#Subturf maps

```{r, fig.height=11, fig.width = 7}
plyr::d_ply(subturf_cover_thin, .(turfID), function(df){
  print(
  ggplot(df, aes(x = (subTurf - 1) %/% 5, y = (subTurf - 1) %% 5, fill = cover)) +
    geom_tile(colour = "grey60") +
    facet_grid(species ~ Year) +
    ggtitle(paste("Plot", df$turfID, "at", df$siteID)) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    scale_fill_distiller(type = "seq", palette = "Greens", direction = 1) + 
    theme_bw() +
    theme(
      axis.text = element_blank(), 
      axis.title = element_blank(), 
      axis.ticks = element_blank(),
      strip.text.y = element_text(angle = 0)
      )
  
  )
    cat("\n")
})
```

